[ 2023-08-03 17:26:30,493 ] 18 root - INFO - [data_validation.py] There is no problem with the data. So, we can continue further. The data passed 'validate()'
[ 2023-08-03 17:26:30,493 ] 19 root - INFO - Data Validation is completed successfully
[ 2023-08-03 17:26:30,495 ] 18 root - INFO - [data_transformation.py] While Handling the data, there's no duplicates. The Data passed the Duplicates Handling phase
[ 2023-08-03 17:26:30,496 ] 30 root - INFO - [data_transformation.py] Got Datatypes of each column successfully
[ 2023-08-03 17:26:30,496 ] 38 root - INFO - [data_transformation.py] There is no problem with the datatype of each column. The data passed 'get_check_dtypes()' successfully.
[ 2023-08-03 17:26:35,571 ] 21 root - INFO - Model saved in the ./data/model/model_y1.pkl directory successfully
[ 2023-08-03 17:26:35,571 ] 25 root - INFO - [model_trainer.py] Models for Y1 are Saved Successfully
[ 2023-08-03 17:26:35,585 ] 27 root - INFO - Model Loaded in the ./data/model/model_y1.pkl directory successfully
[ 2023-08-03 17:26:35,585 ] 22 root - INFO - [model_loader.py] Model is not present is the default location. So, we're going to develop a model
[ 2023-08-03 17:26:35,707 ] 18 root - INFO - [data_validation.py] There is no problem with the data. So, we can continue further. The data passed 'validate()'
[ 2023-08-03 17:26:35,707 ] 19 root - INFO - Data Validation is completed successfully
[ 2023-08-03 17:26:35,707 ] 18 root - INFO - [data_transformation.py] While Handling the data, there's no duplicates. The Data passed the Duplicates Handling phase
[ 2023-08-03 17:26:35,707 ] 30 root - INFO - [data_transformation.py] Got Datatypes of each column successfully
[ 2023-08-03 17:26:35,707 ] 38 root - INFO - [data_transformation.py] There is no problem with the datatype of each column. The data passed 'get_check_dtypes()' successfully.
[ 2023-08-03 17:26:45,238 ] 21 root - INFO - Model saved in the ./data/model/model_y2.pkl directory successfully
[ 2023-08-03 17:26:45,238 ] 34 root - INFO - [model_trainer.py] Models for Y2 are Saved Successfully
[ 2023-08-03 17:26:45,253 ] 27 root - INFO - Model Loaded in the ./data/model/model_y2.pkl directory successfully
[ 2023-08-03 17:26:45,253 ] 39 root - INFO - [model_loader.py] Model is not present is the default location. So, we're going to develop a model
